name: Electron Build
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]   # 这里改成 windows-latest
        
    defaults:
      run:
        working-directory: ./src

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # Windows 机器不需要安装 wine 和 i386 架构，相关步骤可以删除或注释掉
    
    - name: Install dependencies
      run: |
        npm install
        
    - name: electron-builder on Windows
      run: |
        npx electron-builder build --win
        
    - name: Upload artifacts on Windows
      uses: actions/upload-artifact@v4
      with:
        name: win
        path: ./src/dist/*.exe
